title: Chest X-Ray Classification for Tuberculosis Project
description: Project sponsored by the Omdena Myanmar Chapter for classifying chest X-Ray images for pneumonia, tuberculosis, lung cancer,
show_downloads: true
google_analytics:
theme: jekyll-theme-modernist