runtime: python310

instance_class: F4_1G

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
  min_idle_instances: automatic

entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /static
  static_dir: static/
  secure: always
  redirect_http_response_code: 301

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301